theme = "hugo_theme_pickles"
baseurl = ""
languageCode = "en-us"
Title = "Michael Khoo"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Michael Khoo 2017"
relativeurls = false
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  instagram = "mikelkhoo"
  github = "haymike"
  linkedin = "michael-khoo-a957a845"
  # Disqus shortname
  disqus = ""
  # Google Analytics API key.
  ga_api_key = "Your Google Analytics tracking id"
  authorwebsite = "https://haymike.netlify.com"
  author = "Michael Khoo"
  avatar = "https://haymike.netlify.com/images/avatar.jpg"
  contact = "mailto:mlk8qf@gmail.com"
  bio = "University of Virginia '14 graduate currently working as a financial systems analyst at the Federal Reserve Board based in Washington, DC."
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Blog and Data Analysis"
  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "/path/to/favicon"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3
    
